repos:
  - repo: local
    hooks:
      - id: validate-prompts
        name: Validate prompt definitions
        entry: python scripts/validate_prompts.py
        language: python
        additional_dependencies: [jsonschema]
        files: 'prompt_inventory\.json'
