apiVersion: v1
kind: ConfigMap
metadata:
  name: logwatchdog-config
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: logwatchdog
    meta.helm.sh/release-namespace: default
data:
  config.yaml: |-
{{ .Files.Get "config/config.yaml" | indent 4 }}
