apiVersion: v1
kind: ServiceAccount
metadata:
  name: logwatchdog-sa
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: logwatchdog
    meta.helm.sh/release-namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logwatchdog-role
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: logwatchdog
    meta.helm.sh/release-namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logwatchdog-rb
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: logwatchdog
    meta.helm.sh/release-namespace: default
subjects:
  - kind: ServiceAccount
    name: logwatchdog-sa
roleRef:
  kind: Role
  name: logwatchdog-role
  apiGroup: rbac.authorization.k8s.io
