name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install package & dependencies
        run: |
          python -m pip install --upgrade pip
          # 1) Install your own code (via setup.py) in editable mode
          pip install -e .
          # 2) Install only third-party libraries
          pip install -r requirements.txt

      - name: Run pytest suite
        run: python -m pytest --maxfail=1 --disable-warnings -q

      # Optional: upload coverage
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
